# Generated by Django 4.1.7 on 2023-12-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetnosql', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
