version: "3"

services:
  django:
    build:
      context: ./projetnosql
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5


  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb
    volumes:
      - ./mongodb_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
