version: "3"

services:
  django:
    build:
      context: ./projetnosql
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mongodb:
    build:
      context: ./mongodb
    volumes:
      - ./mongodb_data:/data/db
